version: "3.8"

services:
  
  gateway.api:
    container_name: gateway.api
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
    ports:
      - "5000:8080"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    depends_on:
      - identity.api
      - company.api
      - invoice.api
      - file-generator.api
    networks:
      - proxybackend
    
#---------------------------------------------------------------------------
    
  rabbitmq:
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: invoice-manager-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - proxybackend
    volumes:
      - ./.containers/invoice-manager-rabbitmq/data/:/var/lib/rabbitmq:rw
      - ./.containers/invoice-manager-rabbitmq/log/:/var/log/rabbitmq:rw
  
#---------------------------------------------------------------------------  
    
  file-generator.api:
    container_name: fileGenerator.api
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "MessageBroker__Host=amqp://invoice-manager-rabbitmq:5672"
      - "MessageBroker__Username=user"
      - "MessageBroker__Password=password"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      - proxybackend
    depends_on:
      - company.api
      - invoice.api
      - identity.api
      - rabbitmq
  
  #---------------------------------------------------------------------------  

  minio:
    container_name: minio
    command: server --console-address ":9001" /data/
    ports:
      - "9001:9001"
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    networks:
      - proxybackend
    volumes:
      - ./.containers/minio-storage:/data

  storage.api:
    container_name: storage.api
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "MinIOStorage__Endpoint=minio:9000"
      - "MinIOStorage__AccessKey=user"
      - "MinIOStorage__SecretKey=password"
      - "MessageBroker__Host=amqp://invoice-manager-rabbitmq:5672"
      - "MessageBroker__Username=user"
      - "MessageBroker__Password=password"
    ports:
      - "8080:8080"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      - proxybackend
    depends_on:
      - company.api
      - invoice.api
      - identity.api
      - file-generator.api
      - minio

#---------------------------------------------------------------------------  

  identity.api.database:
    container_name: identity.api.database
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports: 
      - "5432:5432"
    volumes: 
      - ./.containers/identity.api.database:/var/lib/postgresql/data:rw
    networks:
      - proxybackend

  identity.api:
    container_name: identity.api 
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ConnectionStrings__PSQL=Host=identity.api.database;Port=5432;Database=app;Username=user;Password=password;"
    ports:
      - "8000:8080"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3    
    depends_on:
      - identity.api.database
    networks:
      - proxybackend

#---------------------------------------------------------------------------

  company.api.database:
    container_name: company.api.database
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ./.containers/company.api.database:/var/lib/postgresql/data:rw
    networks:
      - proxybackend

  company.api:
    container_name: company.api
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ConnectionStrings__PSQL=Host=company.api.database;Port=5432;Database=app;Username=user;Password=password;"
      - "MessageBroker__Host=amqp://invoice-manager-rabbitmq:5672"
      - "MessageBroker__Username=user"
      - "MessageBroker__Password=password"
    ports:
      - "8001:8080"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    depends_on:
      - company.api.database
      - identity.api
    networks:
      - proxybackend

#---------------------------------------------------------------------------

  invoice.api.database:
    container_name: invoice.api.database
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - ./.containers/invoice.api.database:/var/lib/postgresql/data:rw
    networks:
      - proxybackend

  invoice.api:
    container_name: invoice.api
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ConnectionStrings__PSQL=Host=invoice.api.database;Port=5432;Database=app;Username=user;Password=password;"
      - "MessageBroker__Host=amqp://invoice-manager-rabbitmq:5672"
      - "MessageBroker__Username=user"
      - "MessageBroker__Password=password"
    ports:
      - "8002:8080"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    depends_on:
      - invoice.api.database
      - identity.api
      - company.api
    networks: 
      - proxybackend

#---------------------------------------------------------------------------

volumes:
  minio-storage:
  invoice-manager-rabbitmq:
  invoice.api.database:
  identity.api.database:
  company.api.database:

networks:
  proxybackend:
    name: proxybackend
    driver: bridge