version: "3.8"

services:
  
  gateway.api:
    build:
      context: ./Gateway/GatewayApi
      dockerfile: Dockerfile
  
  # -------------------------------------------------
  
  identity.api.database:
    image: postgres:latest
  
  identity.api:
    build:
      context: ./Services/Identity/IdentityApi
      dockerfile: Dockerfile
      
  # -------------------------------------------------
      
  company.api.database:
    image: postgres:latest
    
  company.api:
    build:
      context: ./Services/Company/CompanyApi
      dockerfile: Dockerfile
      
  # -------------------------------------------------
    
  invoice.api.database:
    image: postgres:latest
    
  invoice.api:
    build:
      context: ./Services/Invoice/InvoiceApi
      dockerfile: Dockerfile
      
  # -------------------------------------------------    