services:
  
  gateway.api:
    build:
      context: .
      dockerfile: Gateway/GatewayApi/Dockerfile

# -------------------------------------------------

  rabbitmq: 
    image: rabbitmq:management

# -------------------------------------------------

  minio:
    image: minio/minio:latest
  
# -------------------------------------------------

  storage.api:
    build:
      context: .
      dockerfile: Services/Storage/StorageApi/Dockerfile

# -------------------------------------------------

  file-generator.api:
    build:
      context: .
      dockerfile: Services/FileGenerator/FileGeneratorApi/Dockerfile

# -------------------------------------------------

  identity.api.database:
    image: postgres:18-alpine
  
# -------------------------------------------------

  identity.api:
    build:
      context: .
      dockerfile: Services/Identity/IdentityApi/Dockerfile
      
# -------------------------------------------------      

  company.api.database:
    image: postgres:18-alpine
  
# -------------------------------------------------
  
  company.api:
    build:
      context: .
      dockerfile: Services/Company/CompanyApi/Dockerfile

# -------------------------------------------------

  invoice.api.database:
    image: postgres:18-alpine 
    
# -------------------------------------------------

  invoice.api:
    build:
      context: .
      dockerfile: Services/Invoice/InvoiceApi/Dockerfile