version: "3.8"

services:
  
  identity.api.database:
    container_name: identity.api.database
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports: 
      - "5432:5432"
    volumes: 
      - identity.api.database:/var/lib/postgresql/data:rw

  identity.api:
    container_name: identity.api 
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ConnectionStrings__PSQL=Host=identity.api.database;Port=5432;Database=app;Username=user;Password=password;"
    ports:
      - "8000:8080"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3    
    depends_on:
      - identity.api.database

volumes:
  identity.api.database: