version: "3.8"

services:
  
  identity.api.database:
    image: postgres:latest
  
  identity.api:
    build:
      context: ./Services/Identity/Identity.Api
      dockerfile: Dockerfile
      
  company.api.database:
    image: postgres:latest
    
  company.api:
    build:
      context: ./Services/Company/CompanyApi
      dockerfile: Dockerfile