version: "3.8"

services:
  
  gateway.api:
    build:
      context: .
      dockerfile: Gateway/GatewayApi/Dockerfile

# -------------------------------------------------

  rabbitmq: 
    image: rabbitmq:management

# -------------------------------------------------

  file-generator.api:
    build:
      context: .
      dockerfile: Services/FileGenerator/FileGeneratorApi/Dockerfile

# -------------------------------------------------

  identity.api.database:
    image: postgres:latest

  identity.api:
    build:
      context: .
      dockerfile: Services/Identity/IdentityApi/Dockerfile
      
# -------------------------------------------------      

  company.api.database:
    image: postgres:latest

  company.api:
    build:
      context: .
      dockerfile: Services/Company/CompanyApi/Dockerfile

# -------------------------------------------------

  invoice.api.database:
    image: postgres:latest

  invoice.api:
    build:
      context: .
      dockerfile: Services/Invoice/InvoiceApi/Dockerfile